// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmZhDSYPLiZEDcfEfVOsssqr1YRxmYk1E',
    appId: '1:315664128137:web:64218415894046a1ee0e58',
    messagingSenderId: '315664128137',
    projectId: 'mastocas-app',
    authDomain: 'mastocas-app.firebaseapp.com',
    storageBucket: 'mastocas-app.appspot.com',
    measurementId: 'G-0X09XE7CG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYuBfTBA5xVWZ1zygM_ZmDrSe_WRz_GRI',
    appId: '1:315664128137:android:dfb6c4e94cc424e6ee0e58',
    messagingSenderId: '315664128137',
    projectId: 'mastocas-app',
    storageBucket: 'mastocas-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZFT8Hq-BOcndh7_CYuCULiiWODxIuqqM',
    appId: '1:315664128137:ios:9231eccb01a91255ee0e58',
    messagingSenderId: '315664128137',
    projectId: 'mastocas-app',
    storageBucket: 'mastocas-app.appspot.com',
    iosBundleId: 'com.example.mascotasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZFT8Hq-BOcndh7_CYuCULiiWODxIuqqM',
    appId: '1:315664128137:ios:9231eccb01a91255ee0e58',
    messagingSenderId: '315664128137',
    projectId: 'mastocas-app',
    storageBucket: 'mastocas-app.appspot.com',
    iosBundleId: 'com.example.mascotasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmZhDSYPLiZEDcfEfVOsssqr1YRxmYk1E',
    appId: '1:315664128137:web:1e6b71649bb990a9ee0e58',
    messagingSenderId: '315664128137',
    projectId: 'mastocas-app',
    authDomain: 'mastocas-app.firebaseapp.com',
    storageBucket: 'mastocas-app.appspot.com',
    measurementId: 'G-5F7HZE1CLR',
  );
}
